- name: wazuh deployment
  hosts: swarm-cluster
  become: yes
  tasks:
    - name: verify docker swarm
      shell: |
        docker info | grep -q "Swarm: active"
        docker node ls
      register: swarm_status

    - name: print output
      debug:
        var: swarm_status.stdout_lines

    - name: copy wazuh stack deployment source code
      copy:
        src: ../stack/
        dest: /home/mozennou/stack/
        owner: mozennou
        group: mozennou
        mode: '0755'

    - name: generate self signed certificates
      command: bash ./stack/security/tls/certs-generator.sh

    # - name: Deploy Wazuh stack
    #   docker_stack:
    #     name: wazuh-stack
    #     compose:
    #       - ./stack/wazuh-stack.yml
    #     state: present