version: "3.9"

networks:
  wazuh-overlay:
    driver: overlay

services:
  nginx:
    image: nginx:mainline-alpine3.22
    hostname: nginx
    networks:
      - wazuh-overlay
    ports:
      - "443:443"
    depends_on:
      - wazuh-dashboard
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
      - source: nginx_cert
        target: /etc/ssl/certs/nginx.crt
      - source: nginx_key
        target: /etc/ssl/private/nginx.key
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any


  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.12.0
    hostname: wazuh.indexer
    networks:
      - wazuh-overlay
    # ports:
    #   - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: any
    configs:
      - source: root_ca
        target: /usr/share/wazuh-indexer/certs/root-ca.pem
      - source: indexer_key
        target: /usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - source: indexer_cert
        target: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - source: admin_cert
        target: /usr/share/wazuh-indexer/certs/admin.pem
      - source: admin_key
        target: /usr/share/wazuh-indexer/certs/admin-key.pem
      - source: wazuh_indexer_yml
        target: /usr/share/wazuh-indexer/opensearch.yml
      - source: internal_users_yml
        target: /usr/share/wazuh-indexer/opensearch-security/internal_users.yml
    # volumes:
    #   - wazuh-indexer-data:/var/lib/wazuh-indexer #ril

  wazuh-manager:
    image: wazuh/wazuh-manager:4.12.0
    hostname: wazuh.master
    networks:
      - wazuh-overlay
    depends_on:
      - wazuh-indexer
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: any
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=${INDEXER_USERNAME}
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    # volumes:
    #   - wazuh-manager-master-ossec:/var/ossec
    #   - master-filebeat-etc:/etc/filebeat
    #   - master-filebeat-var:/var/lib/filebeat #ril
    configs:
      - source: root_ca_manager
        target: /etc/ssl/root-ca.pem
      - source: manager_cert
        target: /etc/ssl/filebeat.pem
      - source: manager_key
        target: /etc/ssl/filebeat.key
      - source: wazuh_manager_conf
        target: /wazuh-config-mount/etc/ossec.conf

  wazuh-worker:
    image: wazuh/wazuh-manager:4.12.0
    hostname: wazuh.worker
    networks:
      - wazuh-overlay
    depends_on:
      - wazuh-indexer
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: any
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=${INDEXER_USERNAME}
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
    # volumes:
    #   - wazuh-manager-worker-ossec:/var/ossec
    #   - worker-filebeat-etc:/etc/filebeat
    #   - worker-filebeat-var:/var/lib/filebeat #ril
    configs:
      - source: root_ca_manager
        target: /etc/ssl/root-ca.pem
      - source: wazuh_worker_cert
        target: /etc/ssl/filebeat.pem
      - source: wazuh_worker_key
        target: /etc/ssl/filebeat.key
      - source: wazuh_worker_conf
        target: /wazuh-config-mount/etc/ossec.conf

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.12.0
    hostname: wazuh{{.Task.Slot}}.dashboard
    depends_on:
      - wazuh-indexer
    # ports:
    #   - 443:5601
    networks:
      - wazuh-overlay
    environment:
      - INDEXER_USERNAME=${INDEXER_USERNAME}
      - INDEXER_PASSWORD=${INDEXER_PASSWORD}
      - WAZUH_API_URL=https://wazuh.master
      - DASHBOARD_USERNAME=${DASHBOARD_USERNAME}
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    deploy:
      replicas: 2
      placement:
        constraints:
          - 'node.role == worker'
      restart_policy:
        condition: any
    # volumes:
    #   - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
    #   - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom #ril
    configs:
      - source: wazuh_dashboard_cert
        target: /usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - source: wazuh_dashboard_key
        target: /usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - source: wazuh_root_ca
        target: /usr/share/wazuh-dashboard/certs/root-ca.pem
      - source: opensearch_dashboards_yml
        target: /usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - source: wazuh_yml
        target: /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml


volumes:
  wazuh-indexer-data:
  wazuh-manager-master-ossec:
  wazuh-manager-worker-ossec:
  master-filebeat-etc:
  master-filebeat-var:
  worker-filebeat-etc:
  worker-filebeat-var:
  wazuh-dashboard-config:
  wazuh-dashboard-custom:

configs:
  root_ca:
    file: ./security/tls/wazuh_ssl_certs/root-ca.pem
  ## indexer
  indexer_key:
    file: ./security/tls/wazuh_ssl_certs/wazuh.indexer-key.pem
  indexer_cert:
    file: ./security/tls/wazuh_ssl_certs/wazuh.indexer.pem
  admin_cert:
    file: ./security/tls/wazuh_ssl_certs/admin.pem
  admin_key:
    file: ./security/tls/wazuh_ssl_certs/admin-key.pem
  wazuh_indexer_yml:
    file: ./config/wazuh_indexer/wazuh.indexer.yml
  internal_users_yml:
    file: ./config/wazuh_indexer/internal_users.yml
  ## manager master
  root_ca_manager:
    file: ./security/tls/wazuh_ssl_certs/root-ca-manager.pem
  manager_cert:
    file: ./security/tls/wazuh_ssl_certs/wazuh.master.pem
  manager_key:
    file: ./security/tls/wazuh_ssl_certs/wazuh.master-key.pem
  wazuh_manager_conf:
    file: ./config/wazuh_manager/wazuh_manager.conf
  ## manager worker
  wazuh_worker_cert:
    file: ./security/tls/wazuh_ssl_certs/wazuh.worker.pem
  wazuh_worker_key:
    file: ./security/tls/wazuh_ssl_certs/wazuh.worker-key.pem
  wazuh_worker_conf:
    file: ./config/wazuh_manager/wazuh_worker.conf
  ## dashboard
  wazuh_dashboard_cert:
    file: ./security/tls/wazuh_ssl_certs/wazuh.dashboard.pem
  wazuh_dashboard_key:
    file: ./security/tls/wazuh_ssl_certs/wazuh.dashboard-key.pem
  wazuh_root_ca:
    file: ./security/tls/wazuh_ssl_certs/root-ca.pem
  opensearch_dashboards_yml:
    file: ./config/wazuh_dashboard/opensearch_dashboards.yml
  wazuh_yml:
    file: ./config/wazuh_dashboard/wazuh.yml
  ## nginx
  nginx_config:
    file: ./config/nginx/nginx.conf
  nginx_cert:
    file: ./security/tls/wazuh_ssl_certs/nginx.crt
  nginx_key:
    file: ./security/tls/wazuh_ssl_certs/nginx.key