name: Deploy Wazuh Stack

on:
  push:
    branches: [ main, tmp ] #ril
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

env:
  NGINX_VERSION: ${{ vars.NGINX_VERSION }}
  WAZUH_VERSION: ${{ vars.WAZUH_VERSION }}

jobs:
  scan:
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: update trivy vulnerability database
        run: trivy image --download-db-only

      - name: scan nginx image
        run: trivy image nginx:$NGINX_VERSION --exit-code 1 --severity HIGH,CRITICAL

      - name: scan wazuh dashboard image
        run: trivy image wazuh/wazuh-dashboard:$WAZUH_VERSION --exit-code 1 --severity HIGH,CRITICAL

      - name: scan wazuh manager image
        run: trivy image wazuh/wazuh-manager:$WAZUH_VERSION --exit-code 1 --severity HIGH,CRITICAL

      - name: scan wazuh indexer image
        run: trivy image wazuh/wazuh-indexer:$WAZUH_VERSION --exit-code 1 --severity HIGH,CRITICAL
